# Generated by Django 5.2.6 on 2025-09-22 07:42

import apps.tasks.utils.set_end_of_month
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=apps.tasks.utils.set_end_of_month.calculate_end_of_month),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very high', 'Very High'), ('critical', 'Critical')], default='medium', max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('PENDING', 'Pending'), ('BLOCKED', 'Blocked')], default='NEW', max_length=15),
        ),
    ]
